# Generated by Django 5.2 on 2025-04-29 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User_profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("manager", "Manager"),
                            ("salesagent", "Sales Agent"),
                        ],
                        default="salesagent",
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=100, null=True)),
                ("product_quantity", models.IntegerField(blank=True, default=0)),
                ("unit_price", models.IntegerField(default=0)),
                ("cost", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "issued_quantity",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "total_quantity",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("type_of_stock", models.CharField(blank=True, max_length=100)),
                ("supplier_name", models.CharField(blank=True, max_length=15)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "category_name",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="karibu.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_quantity", models.IntegerField()),
                ("unit_price", models.IntegerField(default=0)),
                (
                    "amount_recieved",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Cash", "Cash"),
                            ("Credit", "Credit"),
                            ("mobile money", "mobile money"),
                        ],
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("sales_date", models.DateTimeField(auto_now_add=True)),
                (
                    "confirm_quantity",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="karibu.stock"
                    ),
                ),
                (
                    "sales_agent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="karibu.user_profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Credit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("amount", models.IntegerField(blank=True, default=20, null=True)),
                ("date_issued", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateField()),
                ("is_paid", models.IntegerField(blank=True, default=0)),
                ("paid_date", models.DateField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="karibu.user_profile",
                    ),
                ),
            ],
        ),
    ]
