# Generated by Django 5.2 on 2025-04-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karibu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("date", models.DateField(auto_now_add=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name="sale",
            old_name="product_item",
            new_name="product_name",
        ),
    ]
