# Generated by Django 5.2 on 2025-04-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karibu", "0002_receipt_rename_product_item_sale_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="credit",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Pending", "Pending"), ("Paid", "Paid")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="sales_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
