# Generated by Django 5.2 on 2025-04-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karibu", "0003_credit_status_alter_sale_sales_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_profile",
            name="address",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user_profile",
            name="email",
            field=models.EmailField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="user_profile",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="user_profile",
            name="is_manager",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="user_profile",
            name="is_owner",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="user_profile",
            name="is_salesagent",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="user_profile",
            name="phonenumber",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="user_profile",
            name="username",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
