# Generated by Django 5.2 on 2025-05-01 17:27

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("karibu", "0004_user_profile_address_user_profile_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buying",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "type_of_product",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("date", models.DateField(auto_now=True, null=True)),
                (
                    "product_quantity",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("cost", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "dealers_name",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("branch_name", models.CharField(blank=True, max_length=20, null=True)),
                ("contact", models.CharField(blank=True, max_length=15, null=True)),
                ("sell_price", models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="user_profile",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelManagers(
            name="user_profile",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name="credit",
            old_name="customer_phone",
            new_name="contact",
        ),
        migrations.RenameField(
            model_name="credit",
            old_name="amount",
            new_name="due_amount",
        ),
        migrations.RemoveField(
            model_name="credit",
            name="date_issued",
        ),
        migrations.RemoveField(
            model_name="user_profile",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="user_profile",
            name="phonenumber",
        ),
        migrations.RemoveField(
            model_name="user_profile",
            name="role",
        ),
        migrations.AddField(
            model_name="credit",
            name="national_id",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="credit",
            name="product_name",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="credit",
            name="product_type",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="user_profile",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
        migrations.AddField(
            model_name="user_profile",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="user_profile",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to.",
                related_name="userprofile_groups",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user_profile",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AddField(
            model_name="user_profile",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
        migrations.AddField(
            model_name="user_profile",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="user_profile",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="user_profile",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
        migrations.AddField(
            model_name="user_profile",
            name="password",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user_profile",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="userprofile_permissions",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterField(
            model_name="credit",
            name="due_date",
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="credit",
            name="is_paid",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="credit",
            name="paid_date",
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="customer_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="total_amount",
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cash", "Cash"),
                    ("Credit", "Credit"),
                    ("mobile money", "mobile money"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="product_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="karibu.stock",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="product_quantity",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="sales_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="unit_price",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="category_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="karibu.category",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="date_added",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="product_quantity",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="supplier_name",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="type_of_stock",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="unit_price",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="address",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="email",
            field=models.EmailField(max_length=25, null=True),
        ),
    ]
