# Generated by Django 5.2 on 2025-05-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karibu", "0005_buying_alter_user_profile_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="unit_price",
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
