# Generated by Django 5.2 on 2025-05-02 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karibu", "0006_remove_stock_unit_price_alter_user_profile_password"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user_profile",
            options={},
        ),
        migrations.AlterModelManagers(
            name="user_profile",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user_profile",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user_profile",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="user_profile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="user_profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user_profile",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="user_profile",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user_profile",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="user_profile",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="user_profile",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="user_profile",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="user_profile",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="user_profile",
            name="password",
        ),
        migrations.RemoveField(
            model_name="user_profile",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="user_profile",
            name="username",
        ),
        migrations.AddField(
            model_name="user_profile",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="buying",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="credit",
            name="due_amount",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="total_amount",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="unit_price",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="item_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="is_manager",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="is_owner",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="is_salesagent",
            field=models.BooleanField(default=True),
        ),
    ]
