# Generated by Django 5.2 on 2025-05-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karibu", "0008_alter_user_profile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_profile",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="username",
            field=models.CharField(
                blank=True, default=True, max_length=100, null=True, unique=True
            ),
        ),
    ]
