# Generated by Django 5.2 on 2025-05-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("karibu", "0009_alter_user_profile_password_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="credit",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="credit",
            name="paid_date",
        ),
    ]
