# Generated by Django 5.2 on 2025-05-05 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karibu", "0010_remove_credit_is_paid_remove_credit_paid_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Procurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "type_of_product",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "product_quantity",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("cost", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "dealers_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("contact", models.CharField(blank=True, max_length=15, null=True)),
                ("sell_price", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="karibu.branch",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Buying",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(
            model_name="category",
            name="category_name",
        ),
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(default="General", max_length=100),
        ),
        migrations.AddField(
            model_name="credit",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credits",
                to="karibu.branch",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="karibu.branch",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="karibu.branch",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="karibu.branch",
            ),
        ),
        migrations.AddField(
            model_name="user_profile",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="karibu.branch",
            ),
        ),
    ]
