# Generated by Django 5.2 on 2025-05-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karibu", "0011_branch_procurement_delete_buying_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_profile",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
