# Generated by Django 5.2 on 2025-05-05 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karibu", "0012_alter_user_profile_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buying",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "type_of_product",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "product_quantity",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("cost", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "dealers_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "branch_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("contact", models.CharField(blank=True, max_length=15, null=True)),
                ("sell_price", models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.RemoveField(
            model_name="branch",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="category",
            name="name",
        ),
        migrations.RemoveField(
            model_name="credit",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="branch",
        ),
        migrations.AddField(
            model_name="category",
            name="category_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="branch",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="sale",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="karibu.branch",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="karibu.branch",
            ),
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.DeleteModel(
            name="Procurement",
        ),
    ]
