# Generated by Django 5.2 on 2025-05-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("karibu", "0013_buying_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="location",
        ),
    ]
