# Generated by Django 5.2 on 2025-05-05 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karibu", "0014_remove_branch_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buying",
            name="branch_name",
        ),
        migrations.AddField(
            model_name="buying",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="karibu.branch",
            ),
        ),
        migrations.AddField(
            model_name="credit",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="karibu.branch",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="karibu.branch",
            ),
        ),
    ]
