# Generated by Django 5.2 on 2025-05-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karibu", "0015_remove_buying_branch_name_buying_branch_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_profile",
            name="branch",
        ),
        migrations.AddField(
            model_name="user_profile",
            name="branches",
            field=models.ManyToManyField(to="karibu.branch"),
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
