# Generated by Django 5.2 on 2025-05-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karibu", "0016_remove_user_profile_branch_user_profile_branches_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="credit",
            name="product_quantity",
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
