# Generated by Django 5.2 on 2025-05-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karibu", "0017_credit_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="credit",
            name="dispatch_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="credit",
            name="product_name",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
