# Generated by Django 5.2 on 2025-10-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karibu', '0019_stock_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='image',
        ),
    ]
