# Generated by Django 5.2.7 on 2026-03-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karibu', '0020_remove_stock_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
