# Generated by Django 5.2.7 on 2026-03-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karibu', '0021_stock_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='low_stock_threshold',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='unit_of_measure',
            field=models.CharField(blank=True, default='kg', max_length=20, null=True),
        ),
    ]
