# Generated by Django 5.2.7 on 2026-03-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karibu', '0022_stock_low_stock_threshold_stock_unit_of_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
